# Generated by Django 5.1.1 on 2024-10-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_pay_type_alter_payment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="status",
            new_name="payment_status",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="pay_type",
            new_name="payment_type",
        ),
    ]
