# Generated by Django 5.1.1 on 2024-10-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                condition=models.Q(("daily_fee__gte", "0.50")),
                name="daily_fee_gte_0.50",
            ),
        ),
    ]
