# Generated by Django 5.1.1 on 2024-10-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_daily_fee_gte_0_50"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="book",
            name="daily_fee_gte_0.50",
        ),
    ]
