# Generated by Django 5.1.1 on 2024-10-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_book_daily_fee_gte_0_50"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_title_and_author"
            ),
        ),
    ]
